name: Deploy FrontEnd

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/yochambeo-front:latest

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem

      - name: Pull Frontend Image
        run: |
          ssh -i /tmp/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-18-230-195-84.sa-east-1.compute.amazonaws.com << 'EOF'
            
            echo "ir a carpeta raiz"
            cd yochambeo

            echo "parar todos los contenedores"
            docker stop $(docker ps -aq)

            echo "borrar todos los contenedores"
            docker rm $(docker ps -aq)
            
            echo "pull image"
            docker pull maxitrigo/yochambeo-front:latest

            echo "run image"
            docker run -d -p 8080:80 --name yochambeo maxitrigo/yochambeo-front:latest

            echo "borrar imagenes no usadas"
            docker image prune -a -f

          EOF
          
