name: Deploy FrontEnd

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./yochambeo/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/yochambeo-front:latest

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -i /tmp/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-18-225-9-140.us-east-2.compute.amazonaws.com << 'EOF'
            echo "Iniciando sesión en EC2..."

            echo "Bajando y eliminando todos los contenedores..."
            docker rm -f $(docker ps -aq) || true  # Eliminar todos los contenedores

            echo "Bajando y eliminando todas las imágenes de Docker..."
            docker rmi $(docker images -q) || true  # Eliminar todas las imágenes
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/yochambeo-frontend:latest
            docker run -d -p 80:80 --name yochambeo-frontend ${{ secrets.DOCKER_USERNAME }}/yochambeo-frontend:latest

          EOF
